# example netlify.toml
[build]
  command = "npm run build"
  functions = "functions"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run start-frontend & npm run start-backend"
  framework = "create-react-app"
  targetPort = 3000
  port = 5000